apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-{{`{{.region}}`}}
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:latest
        ports:
        - containerPort: 80
